name: Deploy to Dev
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: 157.173.209.61
          username: u154025406.ftptestsmhmajax
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /
          dangerous-clean-slate: false
