name: Deploy to Dev

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: 157.173.209.61
          username: u154025406.ftptestsmhmajax
          password: Y09_dndsY09_dndm
          local-dir: ./
          server-dir: /home/u154025406/domains/testsmhmajax.com/public_html/
          dangerous-clean-slate: true
